### PR TITLE
fix(hfork,notar): prevent uaf by reworking structures to use pool

### LINKED ISSUE #7827: fd_notar stake handling deviates from agave
currently, fd_notar stake handling deviates slightly from agave. agave uses stake values on the current root bank, whereas notar uses stake values based on the epoch of the vote slot. this makes it possible that agave confirms something FD doesn't (and vice versa).

however, this can already happen even if the logic mirrors 1-1 because network propagation of gossip / tpu votes is not guaranteed. marking as lower priority

(also: notar is currently buggy on the epoch transition with tracking who has voted for what slots #7833)

### PR DESCRIPTION
**Pull request by lidatong**
Closes #7827

### CODE REVIEW

File: src/choreo/hfork/fd_hfork.c [hunk 1]
```diff
@@ -1,47 +1,290 @@
...
+   bhm_map  (capacity bhm_max): maps bhm_key_t (block_id, bank_hash) ->
+            bhm_t for O(1) lookup of a specific bank hash matcher.
+
+   blk_pool (capacity per_vtr_max): pool of blk_t elements.  Each blk_t
+            stores per-block metadata (our_bank_hash, replayed, dead,
+            forked, checked) and owns a bhm_dlist of all bhm entries
+            sharing the same block_id.
+
+   blk_map  (capacity per_vtr_max): maps block_id -> blk_t for O(1)
+            lookup of per-block metadata.
```
[the remark this answers is not in the document]
Comment (emwang-jump) [reply src/choreo/hfork/fd_hfork.c]: this is true

File: src/choreo/hfork/fd_hfork.c [hunk 2]
```diff
@@ -171,154 +446,188 @@ fd_hfork_delete( void * hfork ) {
...
-  vtr_t * vtr = vtr_map_query( hfork->vtr_map, *vote_acc, NULL );
-  if( FD_UNLIKELY( !vtr ) ) {
-    FD_TEST( vtr_map_key_cnt( hfork->vtr_map ) < vtr_map_key_max( hfork->vtr_map ) );
-    vtr = vtr_map_insert( hfork->vtr_map, *vote_acc );
-    votes_remove_all( vtr->votes );
-  }
+  /* If voter already voted for this block_id, ignore. */
 
-  /* Only process newer votes (by vote slot) from a given voter. */
+  bhm_key_t     bhm_key = { .block_id = *block_id, .bank_hash = *bank_hash };
```
Comment (emwang-jump) [inline src/choreo/hfork/fd_hfork.c]: align

File: src/choreo/notar/fd_notar.c [hunk 3]
```diff
@@ -15,31 +187,52 @@ fd_notar_new( void * shmem,
...
+  notar->vtr_dlist = vtr_dlist_new( vtr_dl );
 
+  /* Pre-allocate a vtrs set and blk_dlist per slot_map position.  These
+     travel with the slot when fd_map_dynamic backfills during remove. */
+
+  fd_notar_slot_t * slot_join = fd_notar_slot_join( notar->slot_map );
+  for( ulong i = 0UL; i < slot_cnt; i++ ) {
+    void * vtrs     = FD_SCRATCH_ALLOC_APPEND( l, fd_notar_slot_vtrs_align(), fd_notar_slot_vtrs_footprint( vtr_max ) );
+    void * blk_dl   = FD_SCRATCH_ALLOC_APPEND( l, blk_dlist_align(),          blk_dlist_footprint()                   );
+    slot_join[i].vtrs     = fd_notar_slot_vtrs_join( fd_notar_slot_vtrs_new( vtrs, vtr_max ) );
```
Comment (emwang-jump) [inline src/choreo/notar/fd_notar.c]: did you intend to slot_vtrs_join here and in notar_join?

File: src/choreo/votxn/fd_votxn.c [hunk 4]
```diff
@@ -0,0 +1,491 @@
...
+  l = FD_LAYOUT_APPEND( l, 128UL,                sizeof(fd_votxn_t)                                         );
+  l = FD_LAYOUT_APPEND( l, slot_pool_align(),     slot_pool_footprint( slot_max )                            );
+  l = FD_LAYOUT_APPEND( l, slot_map_align(),      slot_map_footprint( slot_map_chain_cnt_est( slot_max ) )   );
+  l = FD_LAYOUT_APPEND( l, slot_dlist_align(),    slot_dlist_footprint()                                     );
+  l = FD_LAYOUT_APPEND( l, blk_pool_align(),      blk_pool_footprint( max )                                  );
+  l = FD_LAYOUT_APPEND( l, blk_map_align(),       blk_map_footprint( blk_map_chain_cnt_est( max ) )          );
+  l = FD_LAYOUT_APPEND( l, vtr_pool_align(),      vtr_pool_footprint( vtr_max )                              );
+  l = FD_LAYOUT_APPEND( l, vtr_map_align(),       vtr_map_footprint( vtr_map_chain_cnt_est( vtr_max ) )      );
+  l = FD_LAYOUT_APPEND( l, vtr_dlist_align(),     vtr_dlist_footprint()                                      );
+  l = FD_LAYOUT_APPEND( l, fd_votxn_slot_vtrs_align(), fd_votxn_slot_vtrs_footprint( vtr_max )                );
```
Comment (emwang-jump) [inline src/choreo/votxn/fd_votxn.c]: align

File: src/choreo/votxn/fd_votxn.c [hunk 5]
```diff
@@ -0,0 +1,491 @@
...
+  void *       slot_map   = FD_SCRATCH_ALLOC_APPEND( l, slot_map_align(),   slot_map_footprint( slot_map_chain_cnt_est( slot_max ) ) );
+  void *       slot_dlist = FD_SCRATCH_ALLOC_APPEND( l, slot_dlist_align(), slot_dlist_footprint()                                  );
+  void *       blk_pool   = FD_SCRATCH_ALLOC_APPEND( l, blk_pool_align(),  blk_pool_footprint( max )                               );
+  void *       blk_map    = FD_SCRATCH_ALLOC_APPEND( l, blk_map_align(),   blk_map_footprint( blk_map_chain_cnt_est( max ) )        );
+  void *       vtr_pool   = FD_SCRATCH_ALLOC_APPEND( l, vtr_pool_align(),  vtr_pool_footprint( vtr_max )                            );
+  void *       vtr_map    = FD_SCRATCH_ALLOC_APPEND( l, vtr_map_align(),   vtr_map_footprint( vtr_map_chain_cnt_est( vtr_max ) )    );
+  void *       vtr_dlist  = FD_SCRATCH_ALLOC_APPEND( l, vtr_dlist_align(), vtr_dlist_footprint()                                    );
+  void *       vtr_set    = FD_SCRATCH_ALLOC_APPEND( l, fd_votxn_slot_vtrs_align(), fd_votxn_slot_vtrs_footprint( vtr_max ) );
```
Comment (emwang-jump) [inline src/choreo/votxn/fd_votxn.c]: align !!!! ✊

File: src/choreo/votxn/fd_votxn.c [hunk 6]
```diff
@@ -0,0 +1,491 @@
...
+
+   Each slot corresponds to a slot and tracks which voters have voted
+   for that slot and all the blks that are associated for that slot.
+   Each slot also tracks all the blks associated with that slot in
+   blk_dlist.
+
+            slot_map                         vtr_map
+     map[0] +--------------------+    map[0] +--------------------+
+            | (slot_t) {         |          | (vtr_t) {          |
+            |   .slot = 100,     |          |   .vote_acc = X,      |
```
Comment (emwang-jump) [inline src/choreo/votxn/fd_votxn.c]: align!!!!1

File: src/choreo/votxn/fd_votxn.c [hunk 7]
```diff
@@ -0,0 +1,491 @@
...
+  votxn->vtr_pool   = vtr_pool_join( votxn->vtr_pool );
+  votxn->vtr_map    = vtr_map_join( votxn->vtr_map );
+  votxn->vtr_dlist  = vtr_dlist_join( votxn->vtr_dlist );
+  votxn->vtr_set    = fd_votxn_slot_vtrs_join( votxn->vtr_set );
+
+  /* Re-join vtrs sets and blk_dlists per slot pool position. */
+
+  for( ulong i = 0UL; i < votxn->slot_max; i++ ) {
+    if( votxn->slot_pool[i].vtrs      ) votxn->slot_pool[i].vtrs      = fd_votxn_slot_vtrs_join( votxn->slot_pool[i].vtrs );
+    if( votxn->slot_pool[i].blk_dlist ) votxn->slot_pool[i].blk_dlist = blk_dlist_join( votxn->slot_pool[i].blk_dlist );
```
Comment (emwang-jump) [inline src/choreo/votxn/fd_votxn.c]: is the `if` needed here?

File: src/choreo/hfork/fd_hfork.c [hunk 8]
```diff
@@ -171,154 +436,174 @@ fd_hfork_delete( void * hfork ) {
...
+  vtr->vte_cnt++;
+
+  bhm->vtr_cnt++;
+  bhm->stake += stake;
 
   /* Check for hard forks. */
 
-  if( FD_LIKELY( blk->replayed ) ) check( hfork, total_stake, candidate, blk->dead, &blk->our_bank_hash );
+  blk->flag = check( blk, bhm, total_stake );
+  return blk;
```
[the remark this answers is not in the document]
Comment (emwang-jump) [reply src/choreo/hfork/fd_hfork.c:522]: think this is right, including the other usages of check()

File: src/discof/tower/fd_tower_tile.c [hunk 9]
```diff
@@ -233,43 +234,78 @@ struct fd_tower_tile {
...
 
     /* If ghost and tower are missing, then we know this is a forward
        confirmation (ie. we haven't replayed the block yet). */
 
     if( FD_UNLIKELY( !ghost_blk || !tower_blk ) ) {
-      if( FD_LIKELY( notar_blk->fwd_level < levels[i] ) ) {
-        notar_blk->fwd_level = levels[i];
-        publishes_push_head( ctx->publishes, (publish_t){ .sig = FD_TOWER_SIG_SLOT_CONFIRMED, .msg = { .slot_confirmed = (fd_tower_slot_confirmed_t){ .level = levels[i], .fwd = 1, .slot = notar_blk->slot, .block_id = notar_blk->block_id } } } );
-      }
+      if( fd_uchar_extract_bit( votes_blk->flags, i+4 ) ) continue; /* already forward confirmed */
```
Comment (emwang-jump) [inline src/discof/tower/fd_tower_tile.c:306]: potentially flags needs docs / something clearer than this +4 🥀

File: src/choreo/votes/fd_votes.c [hunk 10]
```diff
@@ -0,0 +1,494 @@
...
+    /* Rekey the blk to the earlier slot's blk_dlist.  This ensures the
+       blk is cleaned up promptly during publish, preventing an attacker
+       from pinning blk entries to far-future slots. */
+
+    slot_t * old_slot = slot_map_ele_query( votes->slot_map, &blk->slot, NULL, votes->slot_pool );
+    if( FD_LIKELY( old_slot ) ) {
+      blk_dlist_ele_remove( old_slot->blk_dlist, blk, votes->blk_pool );
+      old_slot->blk_cnt--;
+    }
+    blk->slot = vote_slot;
```
Comment (emwang-jump) [inline src/choreo/votes/fd_votes.c:380]: for re-key in the future
