### PR TITLE
[net 2.0] Socket tile

### LINKED ISSUE #4317: [v0.4] multiple net tile regression
Running with multiple net tiles is broken in v0.4 due to a regression

xsk_cnt==0 for all net tiles other than kind_id 0

### PR DESCRIPTION
**Pull request by ripatel-fd**
- **Rename net tile to xdp tile**
- **net 2.0: socket tile**

Closes https://github.com/firedancer-io/firedancer/issues/4339
Closes #4317

### CODE REVIEW

File: src/app/fdctl/run/topos/fd_firedancer.c [hunk 1]
```diff
@@ -383,12 +383,10 @@ fd_topo_initialize( config_t * config ) {
   }
 
   /*                                      topo, tile_name, tile_kind_id, fseq_wksp,   link_name,      link_kind_id, reliable,            polled */
-  FOR(net_tile_cnt) for( ulong j=0UL; j<shred_tile_cnt; j++ )
-                       fd_topob_tile_in(  topo, "net",     i,            "metric_in", "shred_net",    j,            FD_TOPOB_UNRELIABLE, FD_TOPOB_POLLED ); /* No reliable consumers of networking fragments, may be dropped or overrun */
-  FOR(net_tile_cnt)    fd_topob_tile_out( topo, "net",     i,                         "net_shred",    i                                                  );
-
-  FOR(net_tile_cnt) for( ulong j=0UL; j<quic_tile_cnt; j++ )
-                       fd_topob_tile_in(  topo, "net",     i,            "metric_in", "quic_net",     j,            FD_TOPOB_UNRELIABLE, FD_TOPOB_POLLED ); /* No reliable consumers of networking fragments, may be dropped or overrun */
+  for( ulong j=0UL; j<shred_tile_cnt; j++ )
```
Comment (mmcgee-jump) [inline src/app/fdctl/run/topos/fd_firedancer.c:386]: Why did this change?

File: src/app/fdctl/run/topos/fd_frankendancer.c [hunk 2]
```diff
@@ -127,12 +126,10 @@ fd_topo_initialize( config_t * config ) {
...
 
   /*                                      topo, tile_name, tile_kind_id, fseq_wksp,   link_name,      link_kind_id, reliable,            polled */
-  FOR(net_tile_cnt) for( ulong j=0UL; j<quic_tile_cnt; j++ )
-                       fd_topob_tile_in(  topo, "net",     i,            "metric_in", "quic_net",     j,            FD_TOPOB_UNRELIABLE, FD_TOPOB_POLLED ); /* No reliable consumers of networking fragments, may be dropped or overrun */
-  FOR(net_tile_cnt) for( ulong j=0UL; j<shred_tile_cnt; j++ )
-                       fd_topob_tile_in(  topo, "net",     i,            "metric_in", "shred_net",    j,            FD_TOPOB_UNRELIABLE, FD_TOPOB_POLLED ); /* No reliable consumers of networking fragments, may be dropped or overrun */
-  FOR(net_tile_cnt)    fd_topob_tile_out( topo, "net",     i,                         "net_quic",     i                                                  );
-  FOR(net_tile_cnt)    fd_topob_tile_out( topo, "net",     i,                         "net_shred",    i                                                  );
+  for( ulong j=0UL; j<quic_tile_cnt; j++ )
```
Comment (mmcgee-jump) [inline src/app/fdctl/run/topos/fd_frankendancer.c:129]: Don't understand why this changed? You need to subscribe each net to all the quic outs?

File: src/disco/net/sock/fd_sock_tile.c [hunk 3]
```diff
@@ -0,0 +1,539 @@
...
+  }
+
+  int reuseport = 1;
+  if( FD_UNLIKELY( setsockopt( orig_fd, SOL_SOCKET, SO_REUSEPORT, &reuseport, sizeof(int) )<0 ) ) {
+    FD_LOG_ERR(( "setsockopt(SOL_SOCKET,SO_REUSEPORT,1) failed (%i-%s)", errno, fd_io_strerror( errno ) ));
+  }
+
+  struct sockaddr_in saddr = {
+    .sin_family      = AF_INET,
+    .sin_addr.s_addr = 0,
```
Comment (mmcgee-jump) [inline src/disco/net/sock/fd_sock_tile.c:108]: The bind address might be provided in the config file, IIRC? Not sure it's great to default to 0.0.0.0

File: src/disco/net/sock/fd_sock_tile.c [hunk 4]
```diff
@@ -0,0 +1,539 @@
...
+}
+
+/* create_udp_socket creates and configures a new UDP socket for the
+   sock tile at the given file descriptor ID. */
+
+static void
+create_udp_socket( int    sock_fd,
+                   ushort udp_port ) {
+
+  if( FD_UNLIKELY( fcntl( sock_fd, F_GETFD, 0 )!=-1 ) ) {
```
Comment (mmcgee-jump) [inline src/disco/net/sock/fd_sock_tile.c:92]: nit: allow for `EBADF` only, other errnos are a FD_LOG_ERR

File: src/app/fdctl/configure/ethtool-gro.c [hunk 5]
```diff
@@ -18,9 +18,15 @@
 
 static int
 enabled( config_t * const config ) {
+
   /* if we're running in a network namespace, we configure ethtool on
-      the virtual device as part of netns setup, not here */
-  return !config->development.netns.enabled;
+     the virtual device as part of netns setup, not here */
```
Comment (mmcgee-jump) [inline src/app/fdctl/configure/ethtool-gro.c:23]: You can edit the `sysctl` stage too, the weird loopback sysctls don't need to be set there, if we are using sockets.

File: src/disco/net/sock/fd_sock_tile.c [hunk 6]
```diff
@@ -0,0 +1,539 @@
...
+
+/* TX PATH (tango->socket) ********************************************/
+
+static void
+flush_tx_batch( fd_sock_tile_t * ctx ) {
+  ulong batch_cnt = ctx->batch_cnt;
+  int send_cnt = sendmmsg( ctx->tx_sock, ctx->batch_msg, (uint)batch_cnt, MSG_DONTWAIT );
+  if( FD_UNLIKELY( send_cnt<(long)batch_cnt ) ) {
+    if( FD_UNLIKELY( send_cnt<0 ) ) {
+      if( FD_LIKELY( errno==EAGAIN ) ) goto done;
```
Comment (mmcgee-jump) [inline src/disco/net/sock/fd_sock_tile.c:374]: Doesn't this drop as well?

**Review by mmcgee-jump — CHANGES_REQUESTED** [review]
Nice!!! Thank you

**Review by ptaffet-jump — COMMENTED** [review]
Shred changes look good to me

**Review by mmcgee-jump — APPROVED** [review]

**Review by mmcgee-jump — APPROVED** [review]
