### PR TITLE
fix(reasm): configure reasm fec_max from toml and simplify store params

### LINKED ISSUE #6437: Fix fd_reasm_footprint slots
```
  ctx->reasm    = FD_SCRATCH_ALLOC_APPEND( l, fd_reasm_align(), fd_reasm_footprint( 1 << 20 ) );
```
Only holds 32 slots, should be derived from max_live_slots * 32k

### PR DESCRIPTION
**Pull request by lidatong**
Closes #6437

### CODE REVIEW

File: src/app/firedancer/topology.c [hunk 1]
```diff
@@ -1320,6 +1327,8 @@ fd_topo_configure_tile( fd_topo_tile_t * tile,
 
     FD_TEST( tile->replay.funk_obj_id == fd_pod_query_ulong( config->topo.props, "funk", ULONG_MAX ) );
 
+    tile->replay.fec_max = config->firedancer.runtime.max_live_slots * FD_SHRED_BLK_MAX;
+
```
Comment (emwang-jump) [inline src/app/firedancer/topology.c:1329]: remove this one
